name: Keep-Alive

on:
  schedule:
    # Esegue il job ogni 7 ore
    - cron: '0 */7 * * *'
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the app
        # Assicurati che l'indirizzo sia corretto e raggiungibile
        run: curl -I https://vquantpro.it/
